version: '3'
services:
  mysql:
    image: mysql # 使用的镜像
    container_name: learning-mysql # 启动的实例名称
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 123456 # root 用户密码
      TZ: Asia/Shanghai
      MYSQL_DEFAULT_AUTH: mysql_native_password
    ports:
      - "3306:3306" # 端口映射
    volumes:
      - ./.mysql-data:/var/lib/mysql # 将数据目录挂载到本地目录以进行持久化
      - ./mysql-init:/docker-entrypoint-initdb.d # 启动脚本
      - /home/mysql/conf/my.cnf:/etc/mysql/my.cnf
#      - /home/mysql/data2:/var/lib/mysql #使用的是linux路径
    command:
      --lower-case-table-names=1
      --bind-address=0.0.0.0  # 监听所有接口
    restart: always # 崩溃后自动重启
    networks:
      - mynetwork # 指定网络
  nacos:
    image: nacos/nacos-server:v3.1.1-slim
    container_name: learning-nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
      - "8080:8080"
    volumes:
      - ./.nacos-data:/home/nacos/data
    networks:
      - mynetwork
    environment:
      - MODE=standalone # 单节点模式启动
      - PREFER_HOST_MODE=hostname # 支持 hostname
      - TZ=Asia/Shanghai # 控制时区
      - NACOS_AUTH_TOKEN=VGhpc0lzTXlTZWNyZXRLZXlGb3JOQWNvc0F1dGg8888
      - NACOS_AUTH_IDENTITY_KEY=nacos
      - NACOS_AUTH_IDENTITY_VALUE=nacos
networks:
  mynetwork: